### ISSUE TITLE
[1.14.4] Does not seem to work with Forge 1.14.4 - 28.0.45

### ISSUE THREAD

**Issue by feliksen** [MapperTV/embellishcraft#2]
Does not seem to work with Forge 1.14.4 - 28.0.45. Any way to fix this issue?

**Comment by MapperTV** [comment]
I can run it on Forge 28.0.45 fine, are you sure it's not another mod that has some problem? I know some mods are broken after a Forge update that changed things but EmbellishCraft doesn't seem to be affected by it.

**Comment by bloodconfetti** [comment]
[crash-2019-08-08_22.44.05-server.txt](https://github.com/MapperTV/embellishcraft/files/3484785/crash-2019-08-08_22.44.05-server.txt)
Hi, just crashed upon loading up the game after first putting this mod in my Mods folder.

**Comment by MapperTV** [comment]
The logs don't tell which mod is in cause. I replicated your modpack and while I could start it and play, I found that many mods have issues. They seems to not load completely. EmbellishCraft and other mods did not load at first launch, then loaded after a restart of the modpack, causing an existing world to crash at load. This is probably because of the Forge update that changed things around at some point. I'll publish a new version with new blocks soon and it will be built against the latest version of Forge which should make sure my mod get to work correctly. But all mods should update to the latest Forge ASAP otherwise we'll still get those problems.

**Comment by bloodconfetti** [comment]
Yeah :/ I know... I've been working all night loading in mods one by one trying to test which crash upon loading the world, etc. etc. and my game is so broken now because of this forge release that it's pretty much unplayable. I've been trying my best to get any possible helpful information to modmakers but realize it's mostly probably Forge which needs to fix some internal issues.

Thank you for your kind response.

**Comment by MapperTV** [comment]
I just published a new version, hopefully this will help for this issue.

**Comment by bloodconfetti** [comment]
Thank you!!
