### ISSUE TITLE
No data fixer registered for entity embellishcraft:entity_chair

### ISSUE THREAD

**Issue by bloodconfetti** [MapperTV/embellishcraft#3]
Hey just letting you know in case this is an issue, my latest log showed a warning for the above:
[latest.log](https://github.com/MapperTV/embellishcraft/files/3493385/latest.log)

**Comment by MapperTV** [comment]
This bug is not really one, data fixers are for updating data saved in entities from a MC version to another MC version. For this mod, since 1.14 is the first used MC version (1.13 doesn't really count here), there is no necessity to add data fixer. I'll still try to do something to remove the warning but for now I'm clueless as 1.14 is still new.
